# Generated by Django 3.2.9 on 2021-11-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_hostel', models.CharField(max_length=200, null=True)),
                ('room_alloted', models.BooleanField(default=False)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
