# Generated by Django 3.2.9 on 2021-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='student',
        ),
    ]
