# Generated by Django 3.2.9 on 2021-11-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_apply_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name_plural': 'Application'},
        ),
        migrations.RemoveField(
            model_name='apply',
            name='favourite_hostel',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='apply',
            name='CheckOut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='checkIn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
        migrations.AddField(
            model_name='apply',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='room_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('premium', 'Premium')], default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='max_no',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='warden',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
        migrations.AddField(
            model_name='warden',
            name='room_allotted',
            field=models.BooleanField(default=False),
        ),
    ]
