# Generated by Django 3.2.9 on 2021-11-27 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211127_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_no',
            new_name='max_persons',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=5, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
