# Generated by Django 3.2.9 on 2022-01-31 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bed_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.faculty'),
        ),
    ]
