# Generated by Django 3.2.9 on 2022-02-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_alter_student_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allocate',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='reg_no',
            new_name='matric_no',
        ),
        migrations.RenameField(
            model_name='warden',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='warden_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_persons',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_status',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='email',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='room',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='room_allotted',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='title',
        ),
        migrations.AddField(
            model_name='hostel',
            name='caretaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='account.Course'),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='no',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
        migrations.AddField(
            model_name='warden',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'), ('B', 'Both Single and Double Occupancy')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'), ('B', 'Both Single and Double Occupancy')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='warden',
            name='hostel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hostel'),
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
