# Generated by Django 3.2.9 on 2022-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220204_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
