# Generated by Django 3.2.9 on 2022-02-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_student_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hostel'),
        ),
    ]
